### PR TITLE
ARROW-9843: [C++] Implement Between ternary kernel

### PR DESCRIPTION
**Pull request by edponce**
Adds Between ternary kernel with internal dispatching of inclusive options.

### CODE REVIEW

**Comment by edponce** [comment]
@bkmgit This PR is incomplete (only supports input BooleanTypes) but it shows how to do [dispatch at runtime based on input type and `BetweenOptions`](https://github.com/bkmgit/arrow/pull/8/files#diff-368ab7e748bd4432c92d9fdc26b51e131742b968e3eb32a6fcea4b9f02fa36aaR948-R987). I plan to share a full version in the next 2 days.

**Comment by bkmgit** [comment]
Thanks for the example.

**Comment by bkmgit** [comment]
@edponce Am happy to merge this and continue developing it later today.

**Comment by edponce** [comment]
@bkmgit I have reworked this PR a bit, so I will update it in the next 2 hours and you can continue completing it. Does this works for you?

**Comment by bkmgit** [comment]
That is fine. Can start in about 10 hours.

**Comment by edponce** [comment]
@bkmgit I pushed the most recent code in this PR. Feel free to continue development on top of this PR.

Two things to note:
* Currently, [the `Between` kernels registration](https://github.com/bkmgit/arrow/pull/8/files#diff-368ab7e748bd4432c92d9fdc26b51e131742b968e3eb32a6fcea4b9f02fa36aaR807) duplicates the switch-case for `BetweenOptions`. This is the only way to do this at the moment, but can be simplified in the future by placing generator dispatchers in classes (I have a local example using this approach). I am working on a proposal for refactoring parts of the compute layer to simplify and make the codebase more consistent.
* Tests are commented bc I did not update them, need to invoke `CallFunction("between", inputs, options)`.

**Comment by bkmgit** [comment]
@edponce Thanks.

**Pull request merged**
